//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 02:04:34 PM CEST 
//


package com.tsystems.tara.entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tsystems.tara.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tsystems.tara.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Domainobjects }
     * 
     */
    public Domainobjects createDomainobjects() {
        return new Domainobjects();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject }
     * 
     */
    public Domainobjects.Domainobject createDomainobjectsDomainobject() {
        return new Domainobjects.Domainobject();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data }
     * 
     */
    public Domainobjects.Domainobject.Data createDomainobjectsDomainobjectData() {
        return new Domainobjects.Domainobject.Data();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ClientDepartments }
     * 
     */
    public Domainobjects.Domainobject.Data.ClientDepartments createDomainobjectsDomainobjectDataClientDepartments() {
        return new Domainobjects.Domainobject.Data.ClientDepartments();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.NoticeRef }
     * 
     */
    public Domainobjects.Domainobject.Data.NoticeRef createDomainobjectsDomainobjectDataNoticeRef() {
        return new Domainobjects.Domainobject.Data.NoticeRef();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ReturnValues }
     * 
     */
    public Domainobjects.Domainobject.Data.ReturnValues createDomainobjectsDomainobjectDataReturnValues() {
        return new Domainobjects.Domainobject.Data.ReturnValues();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.Operations }
     * 
     */
    public Domainobjects.Domainobject.Data.Operations createDomainobjectsDomainobjectDataOperations() {
        return new Domainobjects.Domainobject.Data.Operations();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ListeCodeAsSet }
     * 
     */
    public Domainobjects.Domainobject.Data.ListeCodeAsSet createDomainobjectsDomainobjectDataListeCodeAsSet() {
        return new Domainobjects.Domainobject.Data.ListeCodeAsSet();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.Client }
     * 
     */
    public Domainobjects.Domainobject.Data.Client createDomainobjectsDomainobjectDataClient() {
        return new Domainobjects.Domainobject.Data.Client();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.CocSignature1 }
     * 
     */
    public Domainobjects.Domainobject.Data.CocSignature1 createDomainobjectsDomainobjectDataCocSignature1() {
        return new Domainobjects.Domainobject.Data.CocSignature1();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.PrintHistoryRef }
     * 
     */
    public Domainobjects.Domainobject.Data.PrintHistoryRef createDomainobjectsDomainobjectDataPrintHistoryRef() {
        return new Domainobjects.Domainobject.Data.PrintHistoryRef();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ClientLanguage }
     * 
     */
    public Domainobjects.Domainobject.Data.ClientLanguage createDomainobjectsDomainobjectDataClientLanguage() {
        return new Domainobjects.Domainobject.Data.ClientLanguage();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ClientDepartments.Entry }
     * 
     */
    public Domainobjects.Domainobject.Data.ClientDepartments.Entry createDomainobjectsDomainobjectDataClientDepartmentsEntry() {
        return new Domainobjects.Domainobject.Data.ClientDepartments.Entry();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.NoticeRef.Entry }
     * 
     */
    public Domainobjects.Domainobject.Data.NoticeRef.Entry createDomainobjectsDomainobjectDataNoticeRefEntry() {
        return new Domainobjects.Domainobject.Data.NoticeRef.Entry();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.ReturnValues.Entry }
     * 
     */
    public Domainobjects.Domainobject.Data.ReturnValues.Entry createDomainobjectsDomainobjectDataReturnValuesEntry() {
        return new Domainobjects.Domainobject.Data.ReturnValues.Entry();
    }

    /**
     * Create an instance of {@link Domainobjects.Domainobject.Data.Operations.Entry }
     * 
     */
    public Domainobjects.Domainobject.Data.Operations.Entry createDomainobjectsDomainobjectDataOperationsEntry() {
        return new Domainobjects.Domainobject.Data.Operations.Entry();
    }

}
